### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by vajahath** [AkashBabu/node-mapred#1]
Rewrite the documentation

**Comment by AkashBabu** [comment]
Hi, thanks for the comments. But if you can specify the requirement in detail, it would  be more helpful for me, as i m a newbie to documentation.

**Comment by vajahath** [comment]
It would be awesome if you put the output also in the docs.

**Comment by AkashBabu** [comment]
I ve updated the doc to include Output.

**Comment by vajahath** [comment]
Awesome ⭐
